name: cs230-proj
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.23.5
  - scipy=1.8.0
  - pandas=1.4.1
  - matplotlib=3.5.1
  - tqdm=4.63
  - scikit-image=0.19.2
  - imgaug=0.4.0
  - opencv=4.5.5
  - pytorch=2.1
  - torchvision=0.16.0
  - pip:
    - pycocotools==2.0.10  # for mask handling, if your scripts use COCO utilities

prefix: "/home/apasco/miniforge3/envs/cs230-proj"